baseURL = 'https://hewett.cc/'
locale = 'en-us'
title = 'Hewett.cc'
theme = 'hugo-ficurinia'

copyright = 'Hewett.cc'

[params.author]
    name = 'Hewett'
    email = ''

description = 'Personal website of Hewett'

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.icons]]
        identifier = "gitlab"
        name = "GitLab"
        url = "https://gitlab.com/gabmus"
        weight = 10
